### ISSUE TITLE
Fail to start DebugServer

### ISSUE THREAD

**Issue by Dark-Existed** [OpenSwiftUIProject/AGDebugKit#2]
Thanks for your nice work! 
But I can't start debug server successfully.
I add a symbolic breakpoint on _ZN2AG11DebugServer5startEj , and at this two places set w0 to 1 to execute the code.

![image](https://github.com/OpenSwiftUIProject/AGDebugKit/assets/24956657/7dc4593e-50c4-4c03-84c5-c2521ed8de09)

After this, I got this problem. Any idea to solve this?

![image](https://github.com/OpenSwiftUIProject/AGDebugKit/assets/24956657/0bf684a5-977e-4fb8-87c8-6a6fdd6ff160)

macOS Verstion: 14.3.1
XCode Version: 15.2

**Comment by Kyle-Ye** [comment]
> I add a symbolic breakpoint on _ZN2AG11DebugServer5startEj , and at this two places set w0 to 1 to execute the code.

The first `reg write w0 1` should not be needed. The default mode is local which is 1.

There is a bug that start function always use 0 instead of the mode param. I'll fix it later.

> After this, I got this problem. Any idea to solve this?

I can reproduce it. You can try the first version when the screenshot is committed.

And I'll fix it ASAP in the next version.

**Comment by Kyle-Ye** [comment]
Find the root issue. AGDebugServerRef is actually not CF-based. You can temporary fix it by updating to use `_ = AGDebugServer.start(mode: mode.rawValue)`.

**Comment by Kyle-Ye** [comment]
Fix this via https://github.com/OpenSwiftUIProject/AGDebugKit/commit/8d267abfa5a8f8ccad624ad0307e8e98342506e9
